// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Nv_lWUibmnCqGkSPhwRpvWZvWiBczoc',
    appId: '1:234669294370:web:fbba91d3649c9b23e89b7b',
    messagingSenderId: '234669294370',
    projectId: 'spotify-app-0101',
    authDomain: 'spotify-app-0101.firebaseapp.com',
    storageBucket: 'spotify-app-0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-lWL-gtqxpoLbFMpVyRNXBePkZr77BI',
    appId: '1:234669294370:android:8d7ce0d49d257985e89b7b',
    messagingSenderId: '234669294370',
    projectId: 'spotify-app-0101',
    storageBucket: 'spotify-app-0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YZN7t0c94RoRUQtpG25QyorDRkD-qsE',
    appId: '1:234669294370:ios:d23a07e6eb5947b9e89b7b',
    messagingSenderId: '234669294370',
    projectId: 'spotify-app-0101',
    storageBucket: 'spotify-app-0101.appspot.com',
    iosBundleId: 'com.maxime.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_YZN7t0c94RoRUQtpG25QyorDRkD-qsE',
    appId: '1:234669294370:ios:d23a07e6eb5947b9e89b7b',
    messagingSenderId: '234669294370',
    projectId: 'spotify-app-0101',
    storageBucket: 'spotify-app-0101.appspot.com',
    iosBundleId: 'com.maxime.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Nv_lWUibmnCqGkSPhwRpvWZvWiBczoc',
    appId: '1:234669294370:web:71f61b56ac4ec8c1e89b7b',
    messagingSenderId: '234669294370',
    projectId: 'spotify-app-0101',
    authDomain: 'spotify-app-0101.firebaseapp.com',
    storageBucket: 'spotify-app-0101.appspot.com',
  );
}
